version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      day: 'monday'
      time: '01:00'
      interval: 'weekly'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
      security-updates:
        applies-to: 'security-updates'
        patterns: ['*']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      day: 'monday'
      time: '01:00'
      interval: 'weekly'
    cooldown:
      default-days: 7
